name: flutter_pulsalytics
version: 1.0.2

description: >-
  Flutter plugin for tracking user interactions via heatmap in web applications. Captures mouse movements, clicks, and screenshots, sending data to the backend and enabling real-time visualization.

homepage: https://github.com/zupiti/pulsalytics
repository: https://github.com/zupiti/pulsalytics
issue_tracker: https://github.com/zupiti/pulsalytics/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
