name: flutter_pulsalytics
version: 1.0.0

description: >-
  Plugin Flutter para rastreamento de interações do usuário via heatmap em aplicações web. Permite capturar movimentos do mouse, cliques e screenshots, enviando dados para backend e visualização em tempo real.

author: Nathan Oliveira <seu-email@exemplo.com>
homepage: https://github.com/seu-usuario/flutter_pulsalytics
repository: https://github.com/seu-usuario/flutter_pulsalytics
issue_tracker: https://github.com/seu-usuario/flutter_pulsalytics/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: HeatmapTrackerPlugin
        fileName: lib/web/heatmap_tracker_plugin_web.dart